const PrivacyPolicyContent = [
  {
    articleHeading: "GENERAL",
    articleId: 1,
    articleContent: [
      {
        id: 1.1,
        content: (
          <>
            Edilitics is managed and operated by Decision Sciences & Analytics
            Private Limited (<b>“Edilitics”</b>, "we", “us”, “our” or
            “Platform”), a company incorporated under the Companies Act, 1956,
            having its registered office at G-3, B-Wing, Annapurna CHS,
            Santacruz East, Mumbai - 400055.
          </>
        ),
      },
      {
        id: 1.2,
        content: (
          <>
            Edilitics is a low-code/no-code data analytics platform for modern
            data teams of all sizes and all business verticals. It is built to
            help code-literate as well as non-code-literate members perform
            sophisticated data analysis with ease through a SaaS (Software as a
            Service) Platform. The Platform{" "}
            <a
              href="https://app.edilitics.com"
              className="text-brandGreen"
              aria-label="Edilitics"
            >
              edilitics.com.
            </a>{" "}
            allows Users to access our products, features, and various data
            integration, data pipelines, data transformation, data visualization
            and machine learning tools and related services.
          </>
        ),
      },
      {
        id: 1.3,
        content: (
          <>
            This privacy policy (“Privacy Policy”), together with the Terms of
            Use (collectively called “Platform Policies”) governs your use of
            the Platform and describes our policies and procedures on the
            collection, use, disclosure, processing, transfer, and storage of
            the information provided to us by you on the Platform. We also
            provide information regarding how you can access and update your
            Personal Information and make certain choices about how your
            Personal Information is used by us. We also provide information on
            the information that we may collect through cookies and log files,
            and our practices regarding such information.
          </>
        ),
      },
      {
        id: 1.4,
        content: (
          <>
            By using, browsing, accessing, or purchasing any Service from the
            Platform you agree to be bound by the terms of this Privacy Policy
            and consent to the collection, storage, possession, dealing,
            handling, sharing, disclosure or transfer of your information in
            accordance with the terms of the Privacy Policy. We shall not use
            the User’s information in any manner except as provided under this
            Privacy Policy. Capitalized terms used herein if not defined shall
            have the same meaning as ascribed to them under the Terms.
          </>
        ),
      },
      {
        id: 1.5,
        content: (
          <>
            This document is an electronic record and is governed by the
            provisions under the Information Technology Act, 2000 and rules made
            thereunder as may be applicable, and the amended provisions
            pertaining to electronic records in various statutes as amended by
            the Information Technology Act, 2000. This electronic record is
            generated by a computer system and does not require any physical or
            digital signatures.
          </>
        ),
      },
      {
        id: 1.6,
        content: (
          <>
            This Privacy Policy sets out the type of information collected from
            the Users, including the nature of the Sensitive Personal Data or
            Information (defined hereinafter), the purpose, means and modes of
            usage of such information and how and to whom we shall disclose or
            transfer such information. You may, at any time, withdraw your
            consent for collection and use of your information including
            Personal Information (defined hereinafter) or Sensitive Personal
            Data or Information by writing to us at{" "}
            <a
              href="mailto:support@edilitics.com"
              aria-label="Mail Us"
              className="termsofuse_A"
            >
              support@edilitics.com
            </a>{" "}
            However, please note that if you withdraw your consent, we may no
            longer be able to provide you with the corresponding service for
            which you have withdrawn your consent. It is hereby clarified that
            your decision to withdraw your consent will not affect the
            processing of Personal Information based on your previous consent
            prior to the withdrawal.
          </>
        ),
      },
      {
        id: 1.7,
        content: (
          <>
            Your privacy is of paramount importance to us. Please take a moment
            to familiarize yourself with our Privacy Policy. If you do not agree
            with any provisions of the Terms or this Privacy Policy, we advise
            you to not use or access the Platform.
          </>
        ),
      },
      {
        id: 1.8,
        content: (
          <>
            This Privacy Policy applies to all current and former users,
            accessing or using Our Platform, or otherwise engaging with us
            through email or other means.
          </>
        ),
      },
      {
        id: 1.9,
        content: (
          <>
            We reserve the right to, at any time, add to, change, update, or
            modify this Policy, with or without prior intimation to you, so
            please review it frequently. Therefore, all the Users are requested
            to regularly visit and review this Policy, as may be updated from
            time to time.
          </>
        ),
      },
    ],
  },

  {
    articleHeading: "Type of Information Collected",
    articleId: 2,
    articleContent: [
      {
        id: 2.1,
        content: (
          <>
            You may be asked to provide your information anytime you visit,
            access, use, or browse the Platform. We may share information and
            use it in a manner consistent with the provisions and scope of this
            Privacy Policy. We may also combine it with other information to
            provide and improve our Services, content, and advertising.
          </>
        ),
      },
      {
        id: 2.2,
        content: (
          <>
            You agree to provide information that is true, correct, up-to-date,
            and accurate. You may access, amend, alter or require deletion of
            your information partially or fully by contacting us at Customer
            Care ID:{" "}
            <a
              href="mailto:support@edilitics.com"
              className="termsofuse_A"
              aria-label="Mail Us"
            >
              support@edilitics.com
            </a>{" "}
          </>
        ),
      },
      {
        id: 2.3,
        content: (
          <>
            We do not knowingly collect Personal Information from any user who
            is under 18 (eighteen) years. If we become aware that we have
            collected the Personal Information of a person below the age of 18
            (eighteen) years, we will take steps to delete the information
            within a reasonable timeframe. If a parent or guardian becomes aware
            that his or her child has provided his/her information on the
            Platform without their consent, he or she shall contact us for the
            deletion of such information. In the event where, in contravention
            to the Privacy Policy and Terms, a person below the age of 18
            (eighteen) uses the services, we shall not be held liable or
            responsible for any damage or injury suffered by such a person.
          </>
        ),
      },
      {
        id: 2.4,
        content: (
          <>
            We may collect a variety of information from you, including your
            name, email address, profile photo, company or entity legal name,
            password, address, phone number, including any other usage and
            interaction details with us or our affiliates. We may collect such
            information which when combined with other pieces of information
            available with us could reasonably allow you to be identified
            (“Sensitive Personal Information”). Sensitive Personal Information
            shall include but is not limited to your full name, personal contact
            numbers, residential address, email address, gender, or date of
            birth.
          </>
        ),
      },
      {
        id: 2.5,
        content: (
          <>
            We may also collect, receive, process or store certain sensitive
            personal data or information consisting of, but not limited to:
            <ul>
              <li>Images, Pictures, Photos</li>
              <li>Password</li>
              <li>
                Financial information such as bank account or credit card or
                debit card or other payment instrument details
              </li>
              <li>Physical, physiological, and mental health condition</li>
              <li>
                Any detail relating to the above Personal Information categories
                as provided to us for providing service; and
              </li>
              <li>
                Any of the information received under above Personal Information
                categories by us for processing, stored or processed under
                lawful contract or otherwise. (Collectively, referred to as
                “Sensitive Personal Data or Information”).
              </li>
            </ul>
          </>
        ),
      },
      {
        id: 2.6,
        content: (
          <>
            Cookies: We use cookies, small text files that uniquely identify
            your browser and enable us to recognize the information you have
            consented to give us, to store certain types of information each
            time you visit any page on our Platform. These cookies do not
            contain any personal information, and you may choose what cookies
            you allow by managing your cookies settings on your browser. This
            will allow you to delete your browser cookies or disable them
            entirely. However, if you choose to disable all cookies, it will
            affect your overall experience with our Platform and may make parts
            of our Platform non-functional or inaccessible to you. Therefore, we
            recommend that you enable cookies for our Platform. The cookies we
            collect are mainly used to serve advertising banners to you, and in
            doing so, we may use the services of third parties. Such third-party
            service providers do not know the name, phone number, address, email
            address, or any personal information about you, and no personal
            information is collected or used in this process. Please note that
            if you do not want Edilitics to deploy cookies in your browser, you
            can opt out by setting your browser to reject cookies. If you choose
            to disable cookies in your browser, you can still use Edilitics’s
            Services, although your ability to use some of the features of the
            Platform may be affected. By using the Services, you consent to
            allowing us to retain all the above-described information in
            anonymous form as long as Edilitics sees fit. The Third Parties use
            of cookies and other technologies help us analyze and provide the
            data. You consent to the processing of data about you by these
            analytics providers in the manner and for the purposes set out in
            this Policy. Please be advised that if you opt out of any service,
            you may not be able to use the full functionality of the Services on
            the Platform.
          </>
        ),
      },
      {
        id: 2.7,
        content: (
          <>
            Web beacons: We use web beacons, images that are part of the web
            pages, also called pixel tags or clear gifs, in combination with
            cookies to understand how you interact with our Platform and the
            content therein. When you disable cookies, web beacons are also
            likely to become ineffective. You can also add browser extensions to
            specifically block web beacons.
          </>
        ),
      },
      {
        id: 2.8,
        content: (
          <>
            From third-party Analytics: Reports on activity, performance
            metrics, usage trends, demographic data from software (such as
            Google Analytics, etc.), which are integrated with our Services on
            the Platform.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "Type of Information Collected",
    articleId: 3,
    articleContent: [
      {
        id: 3.1,
        content: (
          <>
            We may collect a variety of information from you, including your
            name, password, mailing address, phone number, email address, and
            contact preferences, including any other usage and interaction
            details with us or our affiliates. We may collect such information
            which, when combined with other pieces of information available with
            us, could reasonably allow you to be identified (“Personal
            Information”). Personal Information shall include but is not limited
            to your full name, personal contact numbers, residential address,
            email address, gender, or date of birth.
          </>
        ),
      },
      {
        id: 3.2,
        content: (
          <>
            Sensitive Personal Information ("SPI") means such personal
            information which consists of information relating to your:
            <ul>
              <li>Password</li>
              <li>
                Financial information such as bank account or credit card or
                debit card or other payment instrument details
              </li>
              <li>Physical, physiological and mental health condition</li>
              <li>
                Any detail relating to the above Personal Information categories
                as provided to us for providing services on the Platform; and
                such other information specified as constituting SPI under the
                applicable laws of India.
              </li>
            </ul>
          </>
        ),
      },
      {
        id: 3.3,
        content: (
          <>
            Except for any SPI that you choose to provide as part of your
            Edilitics Account or in the course of transacting on the Platform,
            We do not collect any SPI in the course of providing our Services on
            the Platform. Any SPI collected by us shall not be disclosed to any
            third party without your express consent, save as otherwise set out
            in this Policy or the{" "}
            <a
              href="https://edilitics.com/terms-of-use"
              className="text-brandGreen"
              aria-label="Terms Of Use"
            >
              Terms Of Use
            </a>{" "}
            or as required by law. It is clarified that this condition shall not
            apply to publicly available information, including SPI, in relation
            to you that you yourself make available publicly, on the Platform.
          </>
        ),
      },
      {
        id: 3.4,
        content: (
          <>
            However, you acknowledge that in the course of providing the
            Services on the Platform, We may receive SPI, either when you
            voluntarily choose to update your profile with information related
            to your identity, physical and physiological condition, or from such
            content posted by you on the Platform, and you hereby consent and
            agree to allow Us to store and display the SPI collected in this
            manner on the Platform and disclose it in accordance with the terms
            of this Policy.
          </>
        ),
      },
      {
        id: 3.5,
        content: (
          <>
            It is clarified that with respect to any SPI that you may share with
            Us, you have the sole right to determine whether you want to share
            such information with us. Further, with respect to any SPI that you
            may share in the course of updating your profile, you have the right
            to determine the levels of access to such information.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "USE OF INFORMATION COLLECTED",
    articleId: 4,
    articleContent: [
      {
        id: 4.1,
        content: (
          <>
            We may collect, use or process your information including Personal
            Information and Sensitive Personal Information for the following
            purposes:
            <ul>
              <li>
                For creating and giving you access to your registered account on
                the Platform.
              </li>
              <li>
                To develop, deliver, process and improve our Products, services,
                content in order to personalize and improve your experience.
              </li>
              <li>
                To inform you about our Products, services, offers, updates,
                upcoming events, including providing you information in relation
                to order confirmations, invoices, technical notices, security
                alerts.
              </li>
              <li>
                For internal analytical and research purposes such as auditing,
                data analysis and research to improve Our Products, Services and
                customer communications.
              </li>
              <li>
                To meet any legal or regulatory requirement or comply with a
                request from any governmental or judicial authority.
              </li>
              <li>
                To resolve any request, dispute, grievance or complaint raised
                by you in relation to your use of the Platform.
              </li>
              <li>
                Any of the information received under above Personal Information
                categories by us for processing, stored or processed under
                lawful contract or otherwise.
              </li>
            </ul>
          </>
        ),
      },
      {
        id: 4.2,
        content: (
          <>
            We may share your information with specific third-party applications
            that we may or may not have already integrated with the Platform.
            The purposes for which such information is shared shall be for
            providing Services in accordance with the{" "}
            <a
              href="https://edilitics.com/terms-of-use"
              className="text-brandGreen"
              aria-label="Terms Of Use"
            >
              Terms Of Use
            </a>{" "}
            , such as Workflow automation, Tracking website traffic,
            advertising, marketing automation, CRM, User behavior tracking, etc.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "DISCLOSURE OF INFORMATION COLLECTED",
    articleId: 5,
    articleContent: [
      {
        id: 5.1,
        content: (
          <>
            We may from time to time be required to disclose the information
            collected from you to our trusted third party service providers who
            assist us in order to facilitate the provision of services on the
            Platform. For instance, we may share your information with a third
            party payment gateway provider to process transactions on the
            Platform. By using the Platform, you consent to any such disclosure
            of your information with third party service providers. We ensure
            that such third party service providers are bound by reasonable
            confidentiality obligations and/or use, maintain and follow
            generally accepted industry and security standards with respect to
            such information.
          </>
        ),
      },
      {
        id: 5.2,
        content: (
          <>
            We may also disclose your information when such disclosure is
            requisitioned under any law or judicial decree or when we, in our
            sole discretion, deem it necessary in order to protect our rights or
            the rights of other Users, to prevent harm to persons or property,
            to fight fraud and credit risk.
          </>
        ),
      },
      {
        id: 5.3,
        content: (
          <>
            We may also disclose or transfer your information to any third party
            as a part of reorganization or a sale of the assets, division or
            transfer of a part or whole of us. We shall ensure that third
            parties to which we transfer or sell our assets will have
            appropriate confidentiality and security measures, at least as
            protective as those described in this Privacy Policy, to handle your
            Personal Information. You will have the opportunity to opt out of
            any such transfer if the new entity's planned processing of your
            information differs materially from that set forth in this Privacy
            Policy.
          </>
        ),
      },
      {
        id: 5.4,
        content: (
          <>
            A third party payment gateway provider may be required to collect
            certain financial information from you including, but not restricted
            to, your credit/debit card number or your bank account details
            (collectively referred to as “Financial Information”). All Financial
            Information collected from you by such third party payment gateway
            providers will be used only for billing and payment processes. The
            Financial Information collected from you is transacted through
            secure digital platforms of approved payment gateways which are
            under encryption, thereby complying with reasonably expected
            technology standards. The verification of the Financial Information
            shall be accomplished only by you through a process of
            authentication in which we shall have no role to play and hence, we
            shall bear no liability in relation to the same. We shall neither be
            liable nor responsible for any actions or inactions of third party
            payment gateway providers or any breach of conditions,
            representations and warranties given by them. We shall also not be
            obligated to mediate or resolve any dispute or disagreement between
            you and such third party payment service providers.
          </>
        ),
      },
      {
        id: 5.5,
        content: (
          <>
            While we take best efforts to ensure that your information including
            Personal Information, Financial Information and Sensitive Personal
            Information or Data is duly protected by undertaking security
            measures prescribed under applicable laws, you are strongly advised
            to exercise reasonable discretion while providing Personal
            Information or Financial Information while using the services given
            that the Internet is susceptible to security breaches.
          </>
        ),
      },
      {
        id: 5.6,
        content: (
          <>
            Your information may also be transferred, stored or processed in any
            country other than the one where you access the Platform. For
            purposes of sharing or disclosing data in accordance with the
            Privacy Policy, we reserve the right to transfer your information
            outside of your country. By using the Platform, you consent to such
            transfer of your information outside of your country and also within
            our affiliates, subsidiaries and partners whose personnel and
            subcontractors, provided they have agreed to ensure the same level
            of data protection as prescribed under this Privacy Policy and the
            data protection laws of India. The information may be transferred in
            the event it is necessary for the performance of the services,
            operation of the Platform and provision of Products as agreed upon
            between us and the third party.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "SECURITY",
    articleId: 6,
    articleContent: [
      {
        id: 6.1,
        content: (
          <>
            The security of your Personal Information is important to us. We
            have implemented security policies, rules and technical measures, as
            required under applicable law including firewalls, transport layer
            security and other physical and electronic security measures to
            protect the Personal Information that it has under its control from
            unauthorized access, improper use or disclosure, unauthorized
            modification and unlawful destruction or accidental loss. When you
            submit your information on the Platform, your information is
            protected through our security systems. Please note that we use
            international and industry-recognized standards such as per
            applicable laws, rules and regulations.
          </>
        ),
      },
      {
        id: 6.2,
        content: (
          <>
            Your information is contained within secured networks and is only
            accessible by a limited number of authorized persons who have access
            rights to such systems or otherwise require such information for the
            purposes provided in this Policy. These authorized persons are also
            under an obligation to keep such information confidential. We abide
            by the multi-tenant data governance obligations, and ensure that one
            User cannot view other User’s data. We conduct infrastructure
            vulnerability scans on a weekly basis.
          </>
        ),
      },
      {
        id: 6.3,
        content: (
          <>
            All communication with us is safe and encrypted with TLS (Transport
            Layer Security). Through the Platform, we maintain complete audit
            trails for any action taken by any user of that Edilitics Account.
          </>
        ),
      },
      {
        id: 6.4,
        content: (
          <>
            Although we make best possible efforts to transmit and store all the
            information provided by you in a secure operating environment that
            is not open to the public, you understand and acknowledge that there
            is no such thing as complete security and we do not guarantee that
            there will be no unintended disclosures of any information and
            potential security breaches. You agree not to hold us responsible
            for any breach of security or for any action of any third parties
            that receive your Personal Information or events that are beyond our
            reasonable control including, acts of government, computer hacking,
            unauthorized access to computer data and storage device, computer
            crashes, breach of security and encryption, etc.
          </>
        ),
      },
    ],
  },

  {
    articleHeading: "COOKIES POLICY",
    articleId: 7,
    articleContent: [
      {
        id: 7.2,
        content: (
          <>
            Due to the communications standards on the Internet, when you visit,
            access or browse the Platform, we automatically receive the uniform
            resource locator of the site from which you visit, access or browse
            the Platform, details of the website you visit on leaving the
            Platform, the internet protocol (“IP”) of each User’s computer
            operating system, type of web browser the User is using, email
            patterns, and the name of the User’s internet service provider. This
            information is used solely to analyze overall User trends and to
            help us improve our services. Please note that the link between the
            User’s IP address and the User’s personally identifiable information
            is not shared with third parties without such User’s permission or
            except when required by law or to provide or facilitate the User
            with the services.
          </>
        ),
      },
      {
        id: 7.3,
        content: (
          <>
            Notwithstanding the above, the User acknowledges that we reserve the
            right to share some of the aggregate findings, including the
            personal information provided by the Users in an unidentifiable,
            aggregate form, and not the specific data with advertisers,
            sponsors, investors, strategic partners, and others in order to help
            grow the business. The amount of information sent to us depends on
            the settings of the web browser used by the User to access the
            Platforms. The User may refer to the browser used, if the User
            wishes to learn what information is provided to us.
          </>
        ),
      },
      {
        id: 7.4,
        content: (
          <>
            The Platform uses temporary cookies to store certain data. We do not
            store Personal Information in cookies. Information collected by us,
            by any means whatsoever, that does not personally identify the User
            as an individual (such as patterns of utilization described above)
            is exclusively owned by us and may be used by us and third party
            service providers for technical administration of the Platforms,
            user administration, research, development, and other purposes.
          </>
        ),
      },
      {
        id: 7.5,
        content: (
          <>
            You understand that you may set or amend your web browsers to delete
            or disable cookies. If you choose to disable cookies on your
            computer or mobile telecommunication device, it may impair, degrade
            or restrict access to certain areas of the Platform.
          </>
        ),
      },
      {
        id: 7.6,
        content: (
          <>
            We may allow other companies or entities to serve advertisements to
            you. These companies or entities include third party advertisement
            servers, advertisement agencies, advertisement technology vendors
            and research firms. We may target some advertisements to you that
            fit a certain general profile. We do not use Personal Information to
            target advertisements to you. In the course of serving
            advertisements or optimizing the services to its Users, we may allow
            authorized third parties to place or recognize a unique cookie on
            the User’s browser.
          </>
        ),
      },
      {
        id: 7.7,
        content: (
          <>
            You agree and understand that we do not exercise control over third
            party websites displayed as search results or links on the Platform.
            These other sites may place their own cookies or other files on the
            Users’ computer, collect data or solicit personal information from
            the Users, on which we have no control and shall not be held
            responsible or liable.
          </>
        ),
      },
      {
        id: 7.8,
        content: (
          <>
            We do not make any representations concerning the privacy practices
            or policies of such third parties or{" "}
            <a
              href="https://edilitics.com/terms-of-use"
              className="text-brandGreen"
              aria-label="Terms Of Use"
            >
              Terms Of Use
            </a>{" "}
            of such websites, nor do we guarantee the accuracy, integrity, or
            quality of the information, data, text, software, sound,
            photographs, graphics, videos, messages or other materials available
            on such websites. The inclusion or exclusion does not imply any
            endorsement by us of such websites, the websites’ provider, or the
            information on the website.
          </>
        ),
      },
      {
        id: 7.9,
        content: (
          <>
            We may keep records of telephone calls received from and made to
            Users for the purpose of administration of services, research and
            development, training, business intelligence, business development,
            or for User administration. We may share such telephone records with
            third parties when required by law or when required to provide or
            facilitate the User with the services.
          </>
        ),
      },
      {
        id: 7.1,
        content: (
          <>
            You consent to our reproduction/publishing of all testimonials and
            reviews given by you on the Platform in relation to the services or
            the Products. You agree that we may edit the testimonials and
            reviews provided by you and reproduce/publish such edited or
            paraphrased versions of the testimonials and reviews on the
            Platform. If the User has any concerns with the
            reproduction/publication of any testimonial or review provided by
            you, the User may contact us at Customer care id:{" "}
            <a
              href="mailto:support@edilitics.com"
              className="termsofuse_A"
              aria-label="Mail Us"
            >
              support@edilitics.com
            </a>{" "}
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "OPT - OUT POLICY",
    articleId: 8,
    articleContent: [
      {
        id: 8.1,
        content: (
          <>
            The third party service providers with whom we may share information
            provided by you are not permitted to market their own services or
            send promotional emails or engage in promotional communication with
            you.
          </>
        ),
      },
      {
        id: 8.2,
        content: (
          <>
            We provide you with the opportunity to opt-out of receiving
            non-essential, promotional, or marketing-related communication from
            itself or its partners.
          </>
        ),
      },
      {
        id: 8.3,
        content: (
          <>
            If you wish to remove your contact information from all our mailing
            lists and newsletters, you can click on the "unsubscribe" link or
            follow the instructions in each email message. Alternatively, you
            can contact us at Customer care id:{" "}
            <a
              href="mailto:support@edilitics.com"
              className="termsofuse_A"
              aria-label="Mail Us"
            >
              support@edilitics.com
            </a>{" "}
            We reserve the right to limit membership based on availability of
            contact information. All Users will be notified by email prior to
            any actions taken.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "RETENTION OF INFORMATION",
    articleId: 9,
    articleContent: [
      {
        id: 9.1,
        content: (
          <>
            We reserve all the rights to retain your information and any data
            for the period necessary to fulfill the purposes outlined in this
            Privacy Policy unless a longer retention period is required or
            permitted under the applicable law.
          </>
        ),
      },
      {
        id: 9.2,
        content: (
          <>
            If you have signed up for our marketing emails, or for any other
            communication, we will retain your Personal Information so long as
            you have provided your consent to receive such communication.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "UPDATION OF YOUR INFORMATION",
    articleId: 10,
    articleContent: [
      {
        id: 10.1,
        content: (
          <>
            It is important that the Personal Information we hold about you is
            accurate and current. Please keep us informed if your Personal
            Information changes during your relationship with us. In the event
            that you would like to access, correct, delete or object to any
            inaccuracies of the Personal Information provided by you, please
            drop an email to us at{" "}
            <a
              href="mailto:support@edilitics.com"
              className="termsofuse_A"
              aria-label="Mail Us"
            >
              support@edilitics.com
            </a>{" "}
          </>
        ),
      },
      {
        id: 10.2,
        content: (
          <>
            Please note that your access to the Platform or utilization of
            services offered on the Platform, offers or promotions in relation
            to the Products as may be provided by us or our affiliates, may be
            governed by other terms and conditions, policies or guidelines along
            with these Terms (“Additional Terms”). If these Terms are
            inconsistent with any Additional Terms, the Additional Terms will
            control to the extent of such inconsistency with respect to the
            applicable Service. These Terms govern your access and use of the
            Platform as well as any transaction or dealings thereon.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "MODIFICATION",
    articleId: 11,
    articleContent: [
      {
        id: 11.1,
        content: (
          <>
            We reserve the right to amend this Privacy Policy at any time. The
            Privacy Policy, as and when modified, shall be updated on the
            Platform. We encourage you to review this Privacy Policy whenever
            you visit our Platform to understand how your Personal Information
            is used.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "GOVERNING LAW",
    articleId: 12,
    articleContent: [
      {
        id: 12.1,
        content: (
          <>
            The terms of this Privacy Policy shall be governed and construed in
            accordance with the laws of India.
          </>
        ),
      },
      {
        id: 12.2,
        content: (
          <>
            Any dispute regarding or arising out of this Privacy Policy shall be
            subject to the exclusive jurisdiction of the courts in Mumbai,
            Maharashtra.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "SEVERABILITY",
    articleId: 13,
    articleContent: [
      {
        id: 13.1,
        content: (
          <>
            Whenever possible, each section of this Privacy Policy shall be
            interpreted in a manner so as to be valid under applicable law.
          </>
        ),
      },
      {
        id: 13.2,
        content: (
          <>
            However, in the event any provision is held to be prohibited or
            invalid, such provision shall be ineffective only to the extent of
            such prohibition or invalidity, without invalidating the remainder
            of such provision or other remaining provisions of this Privacy
            Policy.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "UPDATION OF YOUR INFORMATION",
    articleId: 14,
    articleContent: [
      {
        id: 14.1,
        content: (
          <>
            If the User has any concerns, feedback, review or any request, the
            User is free to contact the Company at Customer care id:{" "}
            <a
              href="mailto:support@edilitics.com"
              className="termsofuse_A"
              aria-label="Mail Us"
            >
              support@edilitics.com
            </a>{" "}
          </>
        ),
      },
    ],
  },
];

export default PrivacyPolicyContent;
