const TermsOfUseContent = [
  {
    articleHeading: "GENERAL",
    articleId: 1,
    articleContent: [
      {
        id: 1.1,
        content: (
          <>
            Eligibility: You affirm that you are either more than 18 years of
            age or possess legal parental or guardian consent and are fully able
            and competent to enter into the terms, conditions, obligations,
            affirmations, representations, and warranties set forth in these
            Terms, and to abide by and comply with these Terms. You further
            represent and warrant that you are not located in a country that is
            subject to a U.S. Government embargo or that has been designated by
            the U.S. Government as a "terrorist-supporting" country, and that
            you are not listed on any U.S. Government list of prohibited or
            restricted parties. If you are entering into these Terms on behalf
            of an entity, organization, or company (a "Subscribing
            Organization"), you represent and warrant that you have the
            authority to bind such Subscribing Organization and its Affiliates
            to these Terms, and you agree to be bound by these Terms on behalf
            of such Subscribing Organization. In such a case, "You" in these
            Terms means such Subscribing Organization, its Affiliates, and each
            User of the Subscribing Organization.
          </>
        ),
      },
      {
        id: 1.2,
        content: (
          <>
            Please note that your access to the Platform or utilization of
            services offered on the Platform, offers or promotions in relation
            to the Products as may be provided by us or our affiliates, may be
            governed by other terms and conditions, policies, or guidelines
            along with these Terms ("Additional Terms"). If these Terms are
            inconsistent with any Additional Terms, the Additional Terms will
            control to the extent of such inconsistency with respect to the
            applicable Service. These Terms govern your access and use of the
            Platform as well as any transaction or dealings thereon.
          </>
        ),
      },
      {
        id: 1.3,
        content: (
          <>
            Please note that we may from time to time change these Terms that
            govern your use of the Platform. Every time you wish to use our
            Platform, please check these Terms to ensure you understand the
            terms and conditions that apply at that time. Further, please note
            that we reserve the right to either change the format and the
            content of the Platform or suspend the operation of the Platform for
            support or maintenance work, in order to update the content or for
            any other reason, at any time.
          </>
        ),
      },
      {
        id: 1.4,
        content: (
          <>
            Any accessing, browsing, or otherwise using the Platform indicates
            your agreement to these Terms, the{" "}
            <a
              href="https://edilitics.com/privacy-policy"
              className="text-brandGreen"
              aria-label="Privacy Policy"
            >
              Privacy Policy
            </a>{" "}
            of the Platform, and any other policies or guidelines that may be
            applicable on the Platform (collectively called "Platform Policies")
            at the time of your access and usage of the Platform and which may
            be updated from time to time ("the Agreement").
          </>
        ),
      },
      {
        id: 1.5,
        content: (
          <>
            This document is an electronic record in terms of the Information
            Technology Act, 2000, and rules made thereunder as may be
            applicable, and the amended provisions pertaining to electronic
            records in various statutes as amended by the Information Technology
            Act, 2000. This electronic record is generated by a computer system
            and does not require any physical or digital signatures.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "USE & REGISTRATION OF PLATFORM",
    articleId: 2,
    articleContent: [
      {
        id: 2.1,
        content: (
          <>
            In order to avail of the Service on the Platform, all you need to do
            is visit{" "}
            <a
              href="https://app.edilitics.com"
              className="text-brandGreen"
              aria-label="Privacy Policy"
            >
              edilitics.com.
            </a>{" "}
            and register yourself for using the Platform.
          </>
        ),
      },
      {
        id: 2.2,
        content: (
          <>
            Process of Registration: It is straightforward! Sign up on the
            Platform by using your email ID or phone number and filling up basic
            information, including a valid email address and any other
            information indicated as required, and your Edilitics account
            ("Account") is created! Registration is a one-time process and is
            free of cost. Edilitics may reject your application for opening an
            account or may cancel an existing account for any reason, at its
            sole discretion.
          </>
        ),
      },
      {
        id: 2.3,
        content: (
          <>
            You are solely authorized to operate the account created by you.
            Consequently, it is your responsibility to maintain the
            confidentiality of the login credentials of your account on the
            Platform and to restrict access to your computer/mobile/other
            similar devices to prevent unauthorized access to your account. You
            shall remain solely liable for all the actions undertaken through
            your account.
          </>
        ),
      },
      {
        id: 2.4,
        content: (
          <>
            You will: (a) immediately inform us of any unauthorized use of the
            account or any other security breach; and (b) ensure that you log
            out of your account at the end of each session. We, our employees,
            agents, directors, and officers will not be liable for any loss or
            direct or indirect damage arising from your failure to comply with
            these Terms of Use. You may be held liable for any losses incurred
            to us or any other user due to unauthorized use of their account by
            you. We reserve the right to refuse access to the Platform,
            terminate accounts, remove or edit content at any time without
            notice to you.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "COMMUNICATION AND UNSUBSCRIPTION",
    articleId: 3,
    articleContent: [
      {
        id: 3.1,
        content: (
          <>
            By accepting the Terms of Use, you also accept to receive news,
            updates, offers/campaign-related SMS to the mobile phone number
            provided by you. By accessing and using the Platform and/or
            verifying your contact number with us, you explicitly consent to
            receive such communications (through call, SMS, email, or other
            digital and electronic means) from us and/or our authorized
            representatives regarding any new services or offerings, even if
            your contact number is registered under the DND/NCPR list under the
            Telecom Commercial Communications Customer Preference Regulations,
            2018.
          </>
        ),
      },
      {
        id: 3.2,
        content: (
          <>
            You can unsubscribe/opt-out from receiving marketing/promotional
            communications, newsletters, and other notifications from us at any
            time by following the instructions set out in such communications.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "PAYMENT",
    articleId: 4,
    articleContent: [
      {
        id: 4.1,
        content: (
          <>
            Invoicing and Payment : Access to the Services or certain features
            of the Services may, now or in the future, require the payment of
            fees such as subscription fees (“Fees”). Fees may be set forth on
            our pricing page available at{" "}
            <a
              href="https://app.edilitics.com"
              className="text-brandGreen"
              aria-label="Privacy Policy"
            >
              edilitics.com.
            </a>{" "}
            or on a physical, electronic, or online Order Form, as applicable,
            which describes such Fees. Edilitics will charge Fees in US dollars
            or such other currency as specified in the relevant Order Form.
            Except as otherwise provided herein, all Fees are non-refundable.
            Edilitics may add new features to the Services on a going-forward
            basis at any time and may charge additional Fees separately for such
            additional features if you elect to use them. Edilitics reserves the
            right to change the Fees charged for any subscription upon the
            renewal of such subscription. The Initial Term and any Renewal Term
            of such subscription shall be as set forth in the applicable Order
            Form.Unless a different payment method is specified otherwise in the
            applicable Order Form, Edilitics will invoice you in accordance with
            the relevant Order Form Terms. Unless otherwise stated in the Order
            Form, invoiced Fees are due fifteen (15) days from the invoice date.
            If the applicable Order Form states that payment will be by credit
            card, you will provide Edilitics with valid and updated credit card
            information, and you shall authorize Edilitics to charge such credit
            card for all Fees due under the Order Form in accordance with the
            billing frequency stated on such Order Form. You are responsible for
            maintaining complete and accurate billing and contact information
            and notifying Edilitics of any changes to such information. If your
            payment method fails or your accounts are past due, (a) you agree to
            pay all amounts due upon demand by Edilitics, (b) Edilitics may
            collect fees owed using other collection mechanisms (including
            charging other payment methods you may have on record with
            Edilitics), (c) Edilitics reserves the right to either suspend or
            terminate your Account or access to the Service, and/or (d) you
            agree to pay a late fee of 1.5% per month or the maximum charge
            permitted by law, whichever is less.
          </>
        ),
      },
      {
        id: 4.2,
        content: (
          <>
            Collection Fee: In the event you fail to pay overdue charges,
            Edilitics may refer your account(s) to a third party for collection.
            You agree that if it becomes necessary for Edilitics to refer your
            invoices to a third party for collection, Edilitics will charge a
            collection fee at the maximum percentage permitted by applicable
            law, but not to exceed 18%, to cover the internal collection-related
            costs Edilitics has incurred on such invoices through and including
            the date on which Edilitics refers the invoices to such third party.
            To the extent permitted by law, you agree to pay Edilitics any
            additional costs and fees Edilitics reasonably incurred to collect
            amounts outstanding on your invoices.You expressly authorize, and
            specifically consent to allow, Edilitics and/or its outside
            collection agencies, outside counsel, or other agents to contact you
            in connection with any and all matters relating to unpaid past due
            charges billed by Edilitics to you. You agree that, for attempts to
            collect unpaid past due charges, such contact may be made to any
            mailing address, telephone number, cellular phone number, e-mail
            address, or any other electronic address that you have provided, or
            may in the future provide, to Edilitics. You agree and acknowledge
            that any e-mail address or any other electronic address that you
            provide to Edilitics is your private address and is not accessible
            to unauthorized third parties.
          </>
        ),
      },
      {
        id: 4.3,
        content: (
          <>
            <strong>Payment Disputes:</strong> Edilitics shall not exercise its
            rights under Section 4.1 (Invoicing and Payment) or 4.2 (Collection
            Fee) with respect to those charges that are under reasonable and
            good faith dispute and for which you are cooperating diligently to
            resolve the dispute.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "PAYMENT",
    articleId: 5,
    articleContent: [
      {
        id: 5.1,
        content: (
          <>
            License from Edilitics to You: Subject to the Terms, Edilitics
            grants you a worldwide, non-exclusive, non-transferable, terminable
            license to use the Services on the Platform.
          </>
        ),
      },
      {
        id: 5.2,
        content: (
          <>
            Customer Personal Data: To the extent applicable, if you input any
            Customer Personal Data for processing through the Services
            (“Customer Data”) within the Services, then you grant Edilitics a
            worldwide, non-exclusive, royalty-free license for the duration of
            this Agreement to use such Customer Data. This usage is solely for
            the purpose of providing the Services to you in accordance with this
            Agreement and other Platform Policies. Edilitics shall not, now or
            in the future, sell any Customer Data to any third party. You are
            solely responsible for storing and maintaining backups and copies of
            all Customer Data, each of which is stored within your applicable
            third-party hosting service provider (such as Google Cloud Platform
            or any other pre-approved platform, as applicable) (the “Cloud
            Provider”). Edilitics is not responsible for storing any Customer
            Data and disclaims all liability in connection with any claims that
            the Customer Data has been lost, deleted, corrupted, or otherwise
            rendered unusable. Edilitics reserves the right to immediately
            suspend your use of the Services or, at any time, to remove any
            Customer Data, with concurrent notice (and provided that Edilitics
            shall endeavor to provide prior notice when possible or permitted).
            This is in instances where the failure to immediately suspend such
            access or remove such Customer Data would violate applicable law or
            cause material and incurable harm to the rights of a third party or
            Edilitics.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "AVAILABILITY AND ACCESSIBILITY OF PLATFORM",
    articleId: 6,
    articleContent: [
      {
        id: 6.1,
        content: (
          <>
            We control and operate this Platform from India and make no
            representation that the materials and the content available on the
            Platform are appropriate for use or will be available for use in
            locations outside India. If you use this Platform from outside
            India, you are entirely responsible for compliance with all
            applicable local laws. These Terms do not constitute, nor may these
            Terms be used for or in connection with, any promotional activities
            or solicitation by anyone in any jurisdiction in which such
            promotional activities or solicitation are not authorized or to any
            person to whom it is unlawful to promote or solicit.
          </>
        ),
      },
      {
        id: 6.2,
        content: (
          <>
            We constantly monitor your account to avoid fraudulent accounts and
            transactions. We reserve the right to initiate legal proceedings
            against such persons for fraudulent use of the Platform and any
            other unlawful acts or omissions in breach of these terms and
            conditions. In the event of detection of any fraudulent or declined
            transaction, prior to the initiation of legal actions, we reserve
            the right to immediately delete such an account and dishonor all
            past and pending orders without any liability. For the purpose of
            this clause, we shall owe no liability for any refunds.
          </>
        ),
      },
      {
        id: 6.3,
        content: (
          <>
            We authorize you to view and access the Platform solely for personal
            and non-commercial use and refrain from any actions that endanger
            the functionality or operation of the Platform. In particular, you
            are prohibited from carrying out any actions that scan or test weak
            points of the Platform, Service, software, bypass security systems,
            or access systems of the software or integrate malware into the
            Platform.
          </>
        ),
      },
      {
        id: 6.4,
        content: (
          <>
            We reserve the right to terminate your access to this Platform at
            any time and without notice. Furthermore, this limited license
            terminates automatically, without notice to you, if you breach any
            of the provisions of these Terms. Upon termination, you must
            immediately destroy any downloaded and printed materials. Any
            provision of the Terms that imposes an obligation or creates a right
            that by its nature will be valid after termination or expiration of
            the Terms shall survive the termination or expiration of the Terms.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "CONFIDENTIALITY",
    articleId: 7,
    articleContent: [
      {
        id: 7.1,
        content: (
          <>
            Definition: As used herein, “Confidential Information” means all
            confidential information disclosed by a party (“Disclosing Party”)
            to the other party (“Receiving Party”), whether orally or in
            writing, that is designated as confidential or that reasonably
            should be understood to be confidential given the nature of the
            information and the circumstances of disclosure. Your Confidential
            Information shall include the Customer Data; Edilitics’s
            Confidential Information shall include the Services; and
            Confidential Information of each party shall include the terms and
            conditions of these Terms and all Work Orders, as well as business
            and marketing plans, technology and technical information, product
            plans and designs, and business processes disclosed by such party.
          </>
        ),
      },
      {
        id: 7.2,
        content: (
          <>
            Exclusions: However, Confidential Information (other than Customer
            Data) shall not include any information that (i) is or becomes
            generally known to the public without a breach of any obligation
            owed to the Disclosing Party, (ii) was known to the Receiving Party
            prior to its disclosure by the Disclosing Party without a breach of
            any obligation owed to the Disclosing Party, (iii) is received from
            a third party without a breach of any obligation owed to the
            Disclosing Party, or (iv) was independently developed by the
            Receiving Party.
          </>
        ),
      },
      {
        id: 7.3,
        content: (
          <>
            Protection of Confidential Information: Except as otherwise
            permitted in writing by the Disclosing Party, (i) the Receiving
            Party shall protect the Disclosing Party’s Confidential Information
            by using the same degree of care that it uses to protect the
            confidentiality of its own confidential information of like kind
            (but in no event less than reasonable care), and shall not disclose
            or use any Confidential Information of the Disclosing Party for any
            purpose outside the scope of these Terms, and (ii) the Receiving
            Party shall limit access to Confidential Information of the
            Disclosing Party to those of its employees, contractors, and agents
            (“Representatives”) who need such access for purposes consistent
            with these Terms and who are bound by confidentiality agreements
            with the Receiving Party containing protections no less stringent
            than those herein.
          </>
        ),
      },
      {
        id: 7.4,
        content: (
          <>
            Compelled Disclosure: The Receiving Party may disclose Confidential
            Information of the Disclosing Party if it is compelled by law to do
            so, provided the Receiving Party gives the Disclosing Party prior
            notice of such compelled disclosure (to the extent legally
            permitted) and reasonable assistance, at the Disclosing Party’s
            cost, if the Disclosing Party wishes to contest the disclosure. If
            the Receiving Party is compelled by law to disclose the Disclosing
            Party's Confidential Information as part of a civil proceeding to
            which the Disclosing Party is a party, and the Disclosing Party is
            not contesting the disclosure, the Disclosing Party will reimburse
            the Receiving Party for its reasonable cost of compiling and
            providing secure access to such Confidential Information.
          </>
        ),
      },
      {
        id: 7.5,
        content: (
          <>
            No License: Except as expressly set forth herein, no license or
            other rights to Confidential Information are granted or implied
            hereby by either party.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: 'ACCEPTABLE USE POLICY ("AUP")',
    articleId: 8,
    articleContent: [
      {
        id: 8.1,
        content: (
          <>
            Use the Services for any illegal purpose or in violation of any
            local, state, national, or international law.
          </>
        ),
      },
      {
        id: 8.2,
        content: <>Copy, modify, or distribute any portion of the Services.</>,
      },
      {
        id: 8.3,
        content: (
          <>
            Violate, or encourage others to violate, the rights of third
            parties.
          </>
        ),
      },
      {
        id: 8.4,
        content: (
          <>
            Import or collect any Customer Data or other content that is
            unlawful, defamatory, libelous, or invasive of privacy or otherwise.
          </>
        ),
      },
      {
        id: 8.5,
        content: (
          <>
            Use the Services to engage in or promote any harmful, offensive,
            inappropriate, fraudulent, deceptive, or illegal activities.
          </>
        ),
      },
      {
        id: 8.6,
        content: (
          <>
            Sell, sublicense, rent, lease, or otherwise transfer the access
            granted herein to the Services or any Materials.
          </>
        ),
      },
      {
        id: 8.7,
        content: (
          <>
            Use or apply, directly or indirectly, the Services in any manner
            competitive with the business of Edilitics.
          </>
        ),
      },
      {
        id: 8.8,
        content: (
          <>
            Use the Services to violate the security or integrity of, or
            otherwise abuse, any application, computing device, system, or
            network (each a “System”) of any party, including but not limited to
            accessing or using any System without permission (including
            attempting to probe, scan, monitor, or test the vulnerability of a
            System), forging any headers or other parts of any message
            describing its origin or routing, interfering with the proper
            functioning of any System (including any deliberate attempt by any
            means to overload a System), implementing denial-of-service attacks
            (inundating a target with communications requests so it cannot
            respond effectively or at all to legitimate traffic), operating
            non-permissioned network services (including open proxies, mail
            relays, or recursive domain name servers), or using any means to
            bypass System usage limitations.
          </>
        ),
      },
      {
        id: 8.9,
        content: (
          <>
            Attempt to gain access to any Systems or networks that connect to
            the Services (except as required to access the Services as provided
            hereunder).
          </>
        ),
      },
      {
        id: 8.1,
        content: (
          <>
            Use the Services to distribute or facilitate the sending of
            unsolicited mass email or other messages, promotions, or
            solicitations (e.g., “spam”), including advertising or other
            announcements of any kind.
          </>
        ),
      },
      {
        id: 8.11,
        content: (
          <>
            Interfere with or disrupt the operation of the Service, including by
            (i) disassembling, decompiling, reverse engineering, or otherwise
            attempting to discover the source code of the Service or any part
            thereof, except to the extent that such activity is expressly
            permitted by applicable law, (ii) performing any fraudulent
            activity, including impersonating any person or entity, claiming
            false affiliations, or accessing the Service accounts of others
            without permission; or (iii) intentionally interfering with or
            damaging the operation of the Service or any user’s enjoyment of it,
            including by uploading or otherwise disseminating viruses or other
            malicious code.
          </>
        ),
      },
      {
        id: 8.12,
        content: (
          <>
            Attempt to gain access to any Systems or networks that connect to
            the Services (except as required to access the Services as provided
            hereunder).
          </>
        ),
      },
      {
        id: 8.13,
        content: (
          <>
            Introduce any trojans, viruses, any other malicious software, any
            bots, or scrape on the Platform for any information.
          </>
        ),
      },
      {
        id: 8.14,
        content: (
          <>Permit or authorize a third party to do any of the foregoing.</>
        ),
      },
    ],
  },
  {
    articleHeading: "DISCLAIMER OF WARRANTIES, INACCURACIES OR ERRORS",
    articleId: 9,
    articleContent: [
      {
        id: 9.1,
        content: (
          <>
            Service Warranty. Edilitics warrants that the Services will
            substantially conform to the functionality set forth herein.
          </>
        ),
      },
      {
        id: 9.2,
        content: (
          <>
            Customer Data Warranty. By importing, storing, or processing
            Customer Data, You affirm, represent, and warrant that:
          </>
        ),
      },
      {
        id: 9.21,
        content: (
          <>
            You are the creator and owner of, or have the necessary licenses,
            rights, consents, and permissions to use and to authorize Edilitics
            and users of the Service to use and distribute Your Customer Data,
            as necessary, to exercise the licenses granted by You in these Terms
            including, but not limited to, Your applicable license agreement
            with the applicable Cloud Provider;
          </>
        ),
      },
      {
        id: 9.22,
        content: (
          <>
            Your Customer Data and the use thereof as contemplated herein, does
            not and will not infringe, violate, or misappropriate any
            third-party right, including any copyright, trademark, patent, trade
            secret, moral right, privacy right, right of publicity, or any other
            intellectual property or proprietary right;
          </>
        ),
      },
      {
        id: 9.3,
        content: (
          <>
            Customer Service Warranty. You agree that Information is being
            supplied to you on the condition that you will make your own
            determination as to the suitability of such information for your
            purpose prior to use or in connection with the making of any
            decision. No Services, offerings or otherwise, (“Information”) on
            the Platform shall constitute an invitation to invest in us or any
            affiliates. Any use of this Platform or the Information is at your
            own risk.
          </>
        ),
      },
      {
        id: 9.4,
        content: (
          <>
            Information Warranty. We will endeavor to ensure that all
            information and recommendations, whether in relation to the
            Information, are correct at the time of inclusion on the Platform.
            We do not guarantee the accuracy of the Information. We make no
            representations or warranties as to the completeness or accuracy of
            Information.
          </>
        ),
      },
      {
        id: 9.5,
        content: (
          <>
            Service Disclaimer. Edilitics does not covenant or provide any
            representations and warranties that the Services will be made
            available at all times.
          </>
        ),
      },
      {
        id: 9.6,
        content: (
          <>
            Use Disclaimer. Neither we, nor our affiliates, nor their officers,
            employees or agents shall be liable for any loss, damage or expense
            arising out of any access to, use of, or reliance upon, this
            website, the Information, or any third-party website linked to this
            Platform. We are not responsible for the content of any third-party
            sites and do not make any representations regarding the content or
            accuracy of material on such sites. If you decide to access links of
            any third-party platforms, you are doing so entirely at your own
            risk and expense.
          </>
        ),
      },
      {
        id: 9.7,
        content: (
          <>
            Customer Data Disclaimer. Except as otherwise set forth herein,
            Edilitics expressly disclaims any and all liability in connection
            with accuracy and source of Customer Data processed using its
            Services. Edilitics is under no obligation to edit or control
            Customer Data that You import to or make available through the
            Services. Edilitics may, at any time without prior notice, remove
            any Customer Data that violates these Terms or applicable law, or
            which violate the rights of a third party or Edilitics.
          </>
        ),
      },
      {
        id: 9.8,
        content: (
          <>
            Nothing contained herein is to be construed as a recommendation to
            use any Service, process, equipment or formulation, in conflict with
            any patent, or otherwise and we make no representation or warranty,
            express or implied that, the use thereof will not infringe any
            patent, or otherwise.
          </>
        ),
      },
      {
        id: 9.9,
        content: (
          <>
            No Sensitive Use. You acknowledge that the Services are not
            designed, intended, or authorized to process sensitive information
            or data, including, but not limited to, protected health information
            as defined under the Health Insurance Portability and Accountability
            Act of 1996 (“HIPAA”), or other sensitive data of You, a User, or a
            third party (collectively “Sensitive Information”). You shall not
            use the Services for such purposes or under such circumstances or to
            process or store Sensitive Information. Edilitics is not aware of,
            and has no method of detecting whether or not any Customer Data
            constitutes Sensitive Information. Edilitics EXPRESSLY DISCLAIMS ANY
            LIABILITY IN CONNECTION WITH ITS ACCESS TO, STORAGE OF, OR
            PROCESSING OF ANY SENSITIVE INFORMATION. You shall indemnify
            Edilitics for any claims arising from Your breach of this Section.
          </>
        ),
      },
      {
        id: "9.10",
        content: (
          <>
            General Disclaimer. THE PLATFORM AND THE SERVICES ARE PROVIDED TO
            YOU ON AN “AS IS” AND “WHERE-IS” BASIS, WITHOUT ANY REPRESENTATIONS
            OR WARRANTIES. WE, FOR OURSELVES AND ANY THIRD-PARTY PROVIDING
            MATERIALS, SERVICES, OR CONTENT TO THIS WEBSITE, MAKE NO
            REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY OR
            OTHERWISE OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR
            NON INFRINGEMENT OF THIRD-PARTY RIGHTS, WITH RESPECT TO THE
            PLATFORM, THE INFORMATION OR ANY PRODUCTS OR SERVICES TO WHICH THE
            INFORMATION REFERS. WE WILL NOT BE LIABLE TO YOU OR ANY THIRD PARTY
            FOR ANY DAMAGES OF ANY KIND, INCLUDING BUT NOT LIMITED TO, DIRECT,
            INDIRECT, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, ARISING
            FROM OR CONNECTED WITH THE SITE, INCLUDING BUT NOT LIMITED TO, YOUR
            USE OF THIS SITE OR YOUR INABILITY TO USE THE SITE, EVEN IF WE HAVE
            PREVIOUSLY BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
          </>
        ),
      },
      {
        id: 9.11,
        content: (
          <>
            Company Disclaimer. To the extent permitted by applicable law, We,
            our officers, agents, employees and directors, disclaim any
            liability against any loss, damage, expenses, liabilities, claim,
            injury caused due to the failure of performance, omission, defect of
            products, or deletion, interruption, error, delay, virus,
            communication, unauthorized access, theft, destruction, alteration
            or use of records on the Platform.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "EXPORT TOOLS AND DISCLAIMER FOR EXPORT TOOLS",
    articleId: 10,
    articleContent: [
      {
        id: 10.1,
        content: (
          <>
            Export Tools. Edilitics may provide tools within the Service that
            enable You to export information, including Customer Data, either in
            downloadable form or directly to third party services (“Export
            Tools”). By using Export Tools to export to third parties services,
            You agree that we may transfer such information, including Customer
            Personal Data, to the applicable service or in the applicable
            format.
          </>
        ),
      },
      {
        id: 10.2,
        content: (
          <>
            Export Tools Disclaimer. YOU ACKNOWLEDGE THAT EXPORT TOOLS MAY NOT
            WORK FOR YOUR PURPOSES, AND YOU ACKNOWLEDGE THAT INFORMATION
            EXPORTED USING EXPORT TOOLS (INCLUDING CUSTOMER DATA) MAY BE
            INCOMPLETE, CORRUPTED, OR OTHERWISE NOT USEABLE.
          </>
        ),
      },
      {
        id: 10.3,
        content: (
          <>
            The disclaimer with respect to Customer Data in Section 10.2 applies
            to all exported Customer Data.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "INTELLECTUAL PROPERTY RIGHTS",
    articleId: 11,
    articleContent: [
      {
        id: 11.1,
        content: (
          <>
            The Platform and its Services are owned and operated by Edilitics.
            The visual interfaces, graphics, design, compilation, information,
            computer code (including source code or object code), products,
            software, services, and all other elements of the Services provided
            by Edilitics (the “Content”) are protected by all relevant
            intellectual property and proprietary rights and applicable laws.
            Except for any Customer Data, all Content contained in the Services
            are the property of Edilitics or its third-party licensors. Except
            as expressly authorized by Edilitics, You may not make use of the
            Content. Edilitics reserves all rights to the Content which is not
            expressly granted in these Terms. You retain copyright and any other
            proprietary rights You hold in the Customer Data that You import to
            the Services.
          </>
        ),
      },
      {
        id: 11.2,
        content: (
          <>
            You may use and display the Content on your personal computer only
            for your personal and internal business use subject to the grant of
            a limited, revocable, personal, non-exclusive and non-transferable
            license to you by us including using and printing copies of the
            Service on the Platform for your personal use and store the files on
            your computer for personal or internal business use only and not for
            commercial purposes.
          </>
        ),
      },
      {
        id: 11.3,
        content: (
          <>
            You may not: (a) copy (whether by printing off onto paper, storing
            on disk, downloading or in any other way), distribute (including
            distributing copies), download, display, perform, reproduce,
            distribute, modify, edit, alter, enhance, broadcast or tamper within
            any way or otherwise use any Content contained on the Platform.
            These restrictions apply in relation to all or part of the Content
            available on the Platform; (b) copy and distribute the Information
            on any other server, or modify or re-use text or graphics on this
            system or another system; (c) reproduce any part of the Content or
            sell or distribute the same for commercial gain nor shall it be
            modified or incorporated in any other work, publication or web site,
            whether in hard copy or electronic format, including postings to any
            other web site; (d) remove any copyright, trademark or other
            intellectual property notices contained in the original material
            from any material copied or printed off from the Content or
            Platform; or (e) link any other material to the Content displayed on
            the Platform, without our express written consent.
          </>
        ),
      },
      {
        id: 11.4,
        content: (
          <>
            The license granted to you does not include a license for: (a)
            resale of Service or commercial use of the Platform or Content, (b)
            use of Service in any derogatory or in violation of any laws, (c)
            any use of Platform, the Services and/or of Content other than as
            contemplated in these Terms, (d) any downloading or copying of login
            credentials of user, (e) any use of data mining, robots, or similar
            data gathering and extraction tools to extract (whether once or many
            times) any parts of Content, and (f) creating and/ or publishing
            your own database that features parts of the Platform.
          </>
        ),
      },
      {
        id: 11.5,
        content: (
          <>
            If you believe that your intellectual property rights have been used
            in a way that raises concerns of infringement, please write to us at{" "}
            <a
              href="mailto:support@edilitics.com"
              className="termsofuse_A"
              aria-label="Privacy Policy"
            >
              support@edilitics.com
            </a>
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "TRADEMARKS",
    articleId: 12,
    articleContent: [
      {
        id: 12.1,
        content: (
          <>
            All the trade names associated with us and all Services and logos
            denoted with "™" on the Platform are trademarks or registered
            trademarks of us or our affiliates. Such trademarks may not be used
            in connection by You, with any product or service that is not our
            product or service.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "INDEMNIFICATION",
    articleId: 13,
    articleContent: [
      {
        id: 13.1,
        content: (
          <>
            <strong>By You:</strong> You agree to indemnify, defend and hold
            harmless us, our affiliates, officers, directors, employees,
            consultants, licensors, agents, and representatives from and against
            (i) any and all third-party claims, losses, liabilities, damages,
            and/or costs (including reasonable attorney fees and costs) arising
            from your access to or use of Platform or the Content or the
            Services, (ii) violation of any of the provisions of these Terms,
            (iii) or infringement of any of our or any third-party intellectual
            property or other rights. We will notify you promptly of any such
            claim, loss, liability, or demand, and in addition to the foregoing,
            you agree to provide us with reasonable assistance, at your expense,
            in defending any such claim, loss, liability, damage, or cost.
          </>
        ),
      },
      {
        id: 13.2,
        content: (
          <>
            <strong>By Edilitics:</strong> Edilitics shall defend, indemnify and
            hold You, and Your respective officers, directors, employees,
            consultants, affiliates, subsidiaries and agents (“Customer
            Indemnitees”) harmless against any loss, damage or costs (including
            reasonable attorneys’ fees) incurred in connection with claims,
            demands, suits, or proceedings (“Claims“) made or brought against
            any Customer Indemnitee by a third party alleging that the use of
            the Service as contemplated hereunder infringes the patent,
            copyright, trade secret or intellectual property or proprietary
            rights of such third party, provided that You (a) give written
            notice of the Claim to Edilitics; (b) give Edilitics control of the
            defense and settlement of the Claim (provided that Edilitics may not
            settle any Claim unless it unconditionally releases You of all
            liability); and (c) provide to Edilitics, at Edilitics cost, all
            reasonable assistance. Edilitics may, at its expense: (i) procure
            for You the right to continue using the Service under the terms of
            these Terms; (ii) replace or modify the Service to be non-infringing
            without a material decrease in functionality; or (iii) if the
            foregoing options are not reasonably practicable, terminate the
            license for the infringing Service and relieve You of any obligation
            to pay fees for the remainder of the term following the effective
            date of termination.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "LIMITATION OF LIABILITY",
    articleId: 14,
    articleContent: [
      {
        id: 14.1,
        content: (
          <>
            IN NO EVENT WILL EDILITICS OR ITS AFFILIATES, BE LIABLE TO YOU FOR
            ANY INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, WHETHER
            BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), STATUTE OR
            ANY OTHER LEGAL THEORY, WHETHER OR NOT EDILITICS OR ITS AFFILIATES
            HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE. YOU AGREE THAT
            THE AGGREGATE LIABILITY OF EDILITICS TO YOU FOR ANY AND ALL CLAIMS
            ARISING FROM OR RELATED TO THE USE OF THE SERVICE IS LIMITED TO THE
            AMOUNTS YOU HAVE PAID TO EDILITICS FOR ACCESS TO AND USE OF THE
            SERVICE IN THE SIX (6) MONTHS PRIOR TO THE CLAIM. SOME JURISDICTIONS
            DO NOT ALLOW THE DISCLAIMER OF WARRANTIES OR LIMITATION OF LIABILITY
            SET FORTH IN THESE TERMS IN CERTAIN CIRCUMSTANCES. ACCORDINGLY, SOME
            OF THE ABOVE LIMITATIONS MAY NOT APPLY.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "APPLICABLE LAW AND JURISDICTION",
    articleId: 15,
    articleContent: [
      {
        id: 15.1,
        content: (
          <>
            These Terms are governed by and to be interpreted in accordance with
            laws of India, without regard to the choice or conflicts of law
            provisions of any jurisdiction. You agree, in the event of any
            dispute arising in relation to these Terms or any dispute arising in
            relation to the Platform whether in contract or tort or otherwise,
            to submit to the jurisdiction of the courts located at Mumbai, India
            for the resolution of all such disputes.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "FORCE MAJEURE",
    articleId: 16,
    articleContent: [
      {
        id: 16.1,
        content: (
          <>
            We will not be held responsible for any delay or failure to comply
            with its obligations if the delay or failure arises from any cause
            which is beyond our reasonable control.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "NO WAIVER",
    articleId: 17,
    articleContent: [
      {
        id: 17.1,
        content: (
          <>
            No provision in these Terms will be deemed waived and no breach
            excused, unless such waiver or consent is in writing and signed by
            us. Any consent by us to, or waiver of your breach, whether
            expressed or implied, will not constitute consent to, waiver of, or
            excuse for any other different or subsequent breach.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "SEVERABILITY",
    articleId: 18,
    articleContent: [
      {
        id: 18.1,
        content: (
          <>
            If any provision of these Terms is held by a court of competent
            jurisdiction to be unenforceable under applicable law, then such
            provision will be excluded from these Terms and the remainder of
            these Terms will be interpreted as if such provision were so
            excluded and will be enforceable in accordance with its terms;
            provided, however, that, in such an event, these Terms will be
            interpreted so as to give effect, to the greatest extent consistent
            with and permitted by applicable law, to the meaning and intention
            of the excluded provision as determined by such court of competent
            jurisdiction.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "AMENDMENT",
    articleId: 19,
    articleContent: [
      {
        id: 19.1,
        content: (
          <>
            These Terms are subject to amendments and modifications and may be
            updated from time to time, without any advance notice. You are
            requested to regularly review the Terms as available on the
            Platform. Your relationship with the Platform will be governed by
            the most current version of these Terms, as published on{" "}
            <a
              href="https://app.edilitics.com"
              className="text-brandGreen"
              aria-label="Privacy Policy"
            >
              edilitics.com.
            </a>
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "UPDATES TO SERVICES",
    articleId: 20,
    articleContent: [
      {
        id: 20.1,
        content: (
          <>
            Edilitics may develop and provide updates, upgrades, enhancements,
            bug fixes, and workarounds for the Services on a regular basis
            ("Updates"). Updates are deemed to be a part of the Services and are
            included at no additional charge.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "NO THIRD PARTY BENEFICIARIES",
    articleId: 21,
    articleContent: [
      {
        id: 21.1,
        content: (
          <>
            These Terms are for the sole benefit of the signatories and are not
            intended to benefit any third party.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "METADATA",
    articleId: 22,
    articleContent: [
      {
        id: 22.1,
        content: (
          <>
            Edilitics may collect aggregate data about Your use of the Services
            that is non-personally identifiable with respect to You or any User
            or individual (“Aggregated Anonymous Data”), and may use and
            disclose the Aggregated Anonymous Data for the purpose of enhancing
            the Services and otherwise for any internal business purpose.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "RELATIONSHIP BETWEEN PARTIES",
    articleId: 23,
    articleContent: [
      {
        id: 23.1,
        content: (
          <>
            Nothing in these Terms shall be construed to create a partnership,
            joint venture, or agency relationship between the parties. Neither
            party will have the power to bind the other or to incur obligations
            on the other’s behalf without such other party’s prior written
            consent.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "SURVIVAL",
    articleId: 24,
    articleContent: [
      {
        id: 24.1,
        content: (
          <>
            Upon termination of the Terms, any provision which, by its nature or
            express terms, should survive, will survive such termination or
            expiration.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "ASSIGNMENT",
    articleId: 25,
    articleContent: [
      {
        id: 25.1,
        content: (
          <>
            Neither party may assign any of its rights or obligations hereunder,
            whether by operation of law or otherwise, without the prior written
            consent of the other party (not to be unreasonably withheld).
            Notwithstanding the foregoing, Edilitics may assign these Terms in
            their entirety (including all Work Orders), without the consent of
            the other party, to its Affiliate or in connection with a merger,
            acquisition, corporate reorganization, or sale of all or
            substantially all of its assets.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "MISCELLANEOUS",
    articleId: 26,
    articleContent: [
      {
        id: 26.1,
        content: (
          <>
            In addition to these Terms of Use, you will also ensure that you are
            in compliance with the terms and conditions of the third parties,
            such as bank offers terms and conditions, brand promotional offers,
            whose links, if any, are contained/embedded in the Services. You
            agree that we will not be liable for any transaction between itself
            and any such third parties. These Terms of Use supersede all
            previous oral and written terms and conditions (if any) communicated
            to you by us, for the use of the Platform, and the rights and
            liabilities with respect to any Services to be provided by us shall
            be limited to the scope of these Terms of Use.
          </>
        ),
      },
    ],
  },
  {
    articleHeading: "FEEDBACK OR CONCERN",
    articleId: 27,
    articleContent: [
      {
        id: 27.1,
        content: (
          <>
            If the User has any concerns, feedback, review or any request, the
            User is free to contact the Company at Customer care id:
            <a
              href="mailto:support@edilitics.com"
              className="text-brandGreen"
              aria-label="Privacy Policy"
            >
              support@edilitics.com
            </a>
          </>
        ),
      },
    ],
  },
];

export default TermsOfUseContent;
